import { Database } from 'sql.js';
import { queryOne, execute, saveDb } from './database';

export function seedDatabase(db: Database): void {
  // Check if NX-102 has investigation, entities, and relationships properly seeded
  const inv = queryOne<{ id: string }>(db, 'SELECT id FROM investigations WHERE id = ?', ['NX-102']);
  const relCount = queryOne<{ count: number }>(db, 'SELECT count(*) as count FROM relationships WHERE investigation_id = ?', ['NX-102']);
  const entCount = queryOne<{ count: number }>(db, 'SELECT count(*) as count FROM entities WHERE investigation_id = ?', ['NX-102']);

  if (inv && inv.id === 'NX-102' && relCount && Number(relCount.count) >= 50 && entCount && Number(entCount.count) >= 30) {
    return;
  }

  console.log('[NetTrace] Initializing demo investigation NX-102 (Phantom Ledger) with full blockchain topology...');

  // Clean old NX-102 data if any exists
  execute(db, 'DELETE FROM relationships WHERE investigation_id = ?', ['NX-102']);
  execute(db, 'DELETE FROM entities WHERE investigation_id = ?', ['NX-102']);
  execute(db, 'DELETE FROM evidence WHERE investigation_id = ?', ['NX-102']);
  execute(db, 'DELETE FROM timeline_events WHERE investigation_id = ?', ['NX-102']);
  execute(db, 'DELETE FROM investigations WHERE id = ?', ['NX-102']);

  // 1. Investigation Record
  execute(
    db,
    `INSERT INTO investigations (
      id, case_number, name, description, status, lead_investigator, agency, classification, total_monitored_funds_usd, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      'NX-102',
      'NX-102',
      'Phantom Ledger',
      'Suspected coordinated cyber-financial network involving phishing infrastructure, multi-sig ransom vaults, CoinJoin tumblers, cross-chain liquidity bridges, and OTC fiat liquidation.',
      'ACTIVE',
      'Special Agent M. Vance',
      'JCAT / Cyber Financial Task Force',
      'TLP:AMBER',
      42850000.0,
      '2026-01-15T08:00:00Z',
      '2026-03-01T14:30:00Z',
    ]
  );

  // 2. Entities (34 entities across all semantic categories)
  const entities = [
    // --- BLOCKCHAIN / FINANCIAL LAYER ---
    // First-Class Blockchain Ledgers
    {
      id: 'ent-chain-btc',
      investigation_id: 'NX-102',
      label: 'BTC-Mainnet (Genesis: 2009)',
      name: 'Bitcoin Mainnet / Blockchain',
      type: 'BLOCKCHAIN',
      threat_level: 'neutral',
      role: 'infrastructure_provider',
      risk_score: 20,
      confidence_score: 99,
      cluster_id: 'cluster-ledgers',
      metadata: JSON.stringify({
        blockchain: 'Bitcoin',
        tags: ['Layer-1', 'Public Ledger', 'Proof-of-Work'],
        status: 'active',
        notes: 'Decentralized distributed ledger recording primary ransomware extortion deposit and peel chains.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-chain-eth',
      investigation_id: 'NX-102',
      label: 'ETH-Mainnet (ChainID: 1)',
      name: 'Ethereum Mainnet / ERC-20 Ledger',
      type: 'BLOCKCHAIN',
      threat_level: 'neutral',
      role: 'infrastructure_provider',
      risk_score: 25,
      confidence_score: 99,
      cluster_id: 'cluster-ledgers',
      metadata: JSON.stringify({
        blockchain: 'Ethereum',
        tags: ['Layer-1', 'Smart Contracts', 'DeFi Liquidity'],
        status: 'active',
        notes: 'Hosts cross-chain liquidity bridge smart contracts and wrapped token swap routes.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-chain-tron',
      investigation_id: 'NX-102',
      label: 'TRON (ChainID: 728126)',
      name: 'TRON Network / TRC-20 Ledger',
      type: 'BLOCKCHAIN',
      threat_level: 'medium',
      role: 'infrastructure_provider',
      risk_score: 60,
      confidence_score: 99,
      cluster_id: 'cluster-ledgers',
      metadata: JSON.stringify({
        blockchain: 'Tron',
        tags: ['USDT Rail', 'High-Velocity', 'Low-Fee Smurfing'],
        status: 'active',
        notes: 'Primary transit network utilized for high-velocity Tether TRC-20 smurfing to Southeast Asian and Middle Eastern mule rings.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },

    // First-Class Transactions
    {
      id: 'ent-tx-1042',
      investigation_id: 'NX-102',
      label: 'TX-1042 (82.4 BTC / $4.8M)',
      name: 'TX-1042 Extortion Payment (BTC)',
      type: 'TRANSACTION',
      threat_level: 'critical',
      role: 'money_launderer',
      risk_score: 96,
      confidence_score: 99,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        txId: 'TX-1042',
        blockchain: 'Bitcoin',
        timestamp: '2025-09-15T14:20:00Z',
        amount: 4800000,
        sender: 'Ascension Care Health Corp',
        receiver: 'Syndicate Master Vault (BTC Treasury)',
        type: 'Ransom Extortion Inflow',
        protocol: 'Bitcoin P2WPKH',
        tags: ['Verified Extortion', 'Duress Payment', 'Direct Inflow'],
        notes: 'Initial ransom payment from Ascension Care following healthcare data lock.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-tx-1043',
      investigation_id: 'NX-102',
      label: 'TX-1043 (288.6 BTC / $16.8M)',
      name: 'TX-1043 CoinJoin Ingestion (BTC)',
      type: 'TRANSACTION',
      threat_level: 'critical',
      role: 'money_launderer',
      risk_score: 94,
      confidence_score: 96,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        txId: 'TX-1043',
        blockchain: 'Bitcoin',
        timestamp: '2025-10-02T09:12:00Z',
        amount: 16800000,
        sender: 'Syndicate Master Vault',
        receiver: 'Wasabi CoinJoin Pool Coordinator',
        type: 'CoinJoin Obfuscation Inflow',
        protocol: 'ZeroLink 100-round Whirlpool',
        tags: ['CoinJoin', 'Tumbling', 'High-Risk Hop'],
        notes: 'Large-scale batching of ransom proceeds into privacy pool.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-tx-1044',
      investigation_id: 'NX-102',
      label: 'TX-1044 (214.8 WBTC / $12.5M)',
      name: 'TX-1044 Cross-Chain Swap (WBTC/ETH)',
      type: 'TRANSACTION',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 93,
      confidence_score: 94,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        txId: 'TX-1044',
        blockchain: 'Ethereum',
        timestamp: '2025-11-14T18:45:00Z',
        amount: 12500000,
        sender: 'Wasabi CoinJoin Pool Coordinator',
        receiver: 'Cross-Chain Liquidity Bridge',
        type: 'Cross-Chain Bridge Swap',
        protocol: 'Wrapped Token Lock & Mint',
        tags: ['Bridge Hop', 'Liquidity Shuffling', 'Chain Crossing'],
        notes: 'Atomic bridge transfer converting tumbled BTC into Ethereum WBTC and USDT liquidity pools.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-tx-1045',
      investigation_id: 'NX-102',
      label: 'TX-1045 (14,200,000 USDT)',
      name: 'TX-1045 Tether TRC20 Mint & Disbursement',
      type: 'TRANSACTION',
      threat_level: 'high',
      role: 'money_launderer',
      risk_score: 88,
      confidence_score: 92,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        txId: 'TX-1045',
        blockchain: 'Tron',
        timestamp: '2025-12-05T11:30:00Z',
        amount: 14200000,
        sender: 'Cross-Chain Liquidity Bridge',
        receiver: 'Tron High-Velocity Tether Pipeline',
        type: 'TRC-20 Transit Transfer',
        protocol: 'TRC-20 Smart Contract Transfer',
        tags: ['USDT Mint', 'Transit Rail', 'Smurfing Source'],
        notes: 'High-volume stablecoin disbursement feeding downstream mule distribution networks.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-tx-1046',
      investigation_id: 'NX-102',
      label: 'TX-1046 (9,600,000 USDT)',
      name: 'TX-1046 OTC Sweep to Dubai Corp Shell',
      type: 'TRANSACTION',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 92,
      confidence_score: 95,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        txId: 'TX-1046',
        blockchain: 'Tron',
        timestamp: '2026-01-10T16:00:00Z',
        amount: 9600000,
        sender: 'Tron High-Velocity Tether Pipeline',
        receiver: 'OTC Broker "Vortex Liquidity"',
        type: 'Bulk OTC Settlement Sweep',
        protocol: 'TRC-20 Settlement',
        tags: ['OTC Liquidation', 'Fiat Offramp', 'Final Stage'],
        notes: 'Direct bulk liquidation of USDT into cash and commercial wire deposits for UAE shell company.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },

    // Wallets
    {
      id: 'ent-wallet-treasury',
      investigation_id: 'NX-102',
      label: 'bc1qa5kx94m23p08qf...82e0',
      name: 'Syndicate Master Vault (BTC Treasury)',
      type: 'WALLET',
      threat_level: 'critical',
      role: 'money_launderer',
      risk_score: 99,
      confidence_score: 98,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        blockchain: 'Bitcoin',
        balanceUSD: 18450000,
        totalVolumeUSD: 31200000,
        firstSeen: '2025-08-20',
        lastSeen: '2026-02-28',
        tags: ['Master Vault', 'Extortion Inflow', 'CoinJoin Aggregator', 'High-Risk'],
        status: 'under_surveillance',
        notes: 'Primary ransom deposit address directly controlled by Dmitri Volkov via 2-of-3 multi-sig.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-wallet-mixer-1',
      investigation_id: 'NX-102',
      label: 'bc1q98xzl70w8e9r2t...44a1',
      name: 'Wasabi CoinJoin Pool Coordinator',
      type: 'WALLET',
      threat_level: 'high',
      role: 'money_launderer',
      risk_score: 88,
      confidence_score: 92,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        blockchain: 'Bitcoin',
        totalVolumeUSD: 16800000,
        firstSeen: '2025-09-01',
        lastSeen: '2026-02-20',
        tags: ['Wasabi Mixer', 'Obfuscation Layer', 'Peel-Chain'],
        status: 'active',
        notes: 'Splits incoming ransom deposits across 250+ zero-link CoinJoin rounds.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-wallet-bridge-eth',
      investigation_id: 'NX-102',
      label: '0x71C9482F5a78...4E92',
      name: 'Cross-Chain Liquidity Bridge (WBTC/USDT)',
      type: 'WALLET',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 95,
      confidence_score: 96,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        blockchain: 'Ethereum',
        totalVolumeUSD: 24500000,
        firstSeen: '2025-10-15',
        lastSeen: '2026-02-25',
        tags: ['Cross-Chain Bridge', 'Liquidity Hopper', 'Single Point of Failure'],
        status: 'active',
        notes: 'Smart contract bridge used to cross BTC liquidity into ERC-20 and TRC-20 stablecoin rails.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-wallet-tron-usdt',
      investigation_id: 'NX-102',
      label: 'TKs92xLp48Vn2k9s0...91Zb',
      name: 'Tron High-Velocity Tether Pipeline',
      type: 'WALLET',
      threat_level: 'high',
      role: 'money_launderer',
      risk_score: 86,
      confidence_score: 90,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        blockchain: 'Tron',
        totalVolumeUSD: 14200000,
        firstSeen: '2025-11-01',
        lastSeen: '2026-02-27',
        tags: ['USDT-TRC20', 'Rapid Transit', 'Smurfing Hub'],
        status: 'active',
        notes: 'High-speed dispersal node routing USDT into Southeast Asian mule networks and OTC brokers.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-wallet-monero-out',
      investigation_id: 'NX-102',
      label: '888tNkZrPN6JsE6...3kLM',
      name: 'Privacy Swap Exit Address (XMR Gateway)',
      type: 'WALLET',
      threat_level: 'critical',
      role: 'money_launderer',
      risk_score: 92,
      confidence_score: 87,
      cluster_id: 'cluster-treasury',
      metadata: JSON.stringify({
        blockchain: 'Monero',
        totalVolumeUSD: 8500000,
        tags: ['Privacy Coin', 'Blind Hop', 'Dark Liquidity'],
        status: 'active',
        notes: 'Atomic swap exit converting $8.5M into Monero (XMR) to sever traceability.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-mule-1',
      investigation_id: 'NX-102',
      label: 'Mule Wallet #108 (TRX)',
      name: 'Smurfing Mule Account (SE Asia 108)',
      type: 'WALLET',
      threat_level: 'high',
      role: 'mule',
      risk_score: 77,
      confidence_score: 89,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        blockchain: 'Tron',
        totalVolumeUSD: 950000,
        tags: ['Smurfing', 'Pass-Through', 'Mule Account'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-mule-2',
      investigation_id: 'NX-102',
      label: 'Mule Wallet #109 (TRX)',
      name: 'Smurfing Mule Account (SE Asia 109)',
      type: 'WALLET',
      threat_level: 'high',
      role: 'mule',
      risk_score: 76,
      confidence_score: 88,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        blockchain: 'Tron',
        totalVolumeUSD: 880000,
        tags: ['Smurfing', 'Pass-Through', 'Mule Account'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-mule-3',
      investigation_id: 'NX-102',
      label: 'Mule Wallet #110 (TRX)',
      name: 'Smurfing Mule Account (SE Asia 110)',
      type: 'WALLET',
      threat_level: 'high',
      role: 'mule',
      risk_score: 75,
      confidence_score: 87,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        blockchain: 'Tron',
        totalVolumeUSD: 920000,
        tags: ['Smurfing', 'Pass-Through', 'Mule Account'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },

    // Exchanges
    {
      id: 'ent-exchange-binance',
      investigation_id: 'NX-102',
      label: 'Binance Hot Wallet 6',
      name: 'Tier-1 Exchange Inflow (Binance KYC Gateway)',
      type: 'EXCHANGE',
      threat_level: 'medium',
      role: 'money_launderer',
      risk_score: 65,
      confidence_score: 97,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        totalVolumeUSD: 7200000,
        tags: ['Regulated Exchange', 'KYC Subpoena Target', 'Law Enforcement Liaison'],
        status: 'subpoena_pending',
        notes: 'Deposit gateway for verified account holders receiving layered transfers.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-exchange-kucoin',
      investigation_id: 'NX-102',
      label: 'KuCoin Unverified Deposit Hub',
      name: 'KuCoin Sub-Account Pool',
      type: 'EXCHANGE',
      threat_level: 'high',
      role: 'money_launderer',
      risk_score: 81,
      confidence_score: 93,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        totalVolumeUSD: 4900000,
        tags: ['Offshore Exchange', 'No-KYC Deposit', 'High-Risk Offramp'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },

    // --- CYBER INFRASTRUCTURE LAYER ---
    {
      id: 'ent-ip-c2-1',
      investigation_id: 'NX-102',
      label: '185.220.101.5',
      name: 'Bulletproof C2 Server (Moldova)',
      type: 'IP',
      threat_level: 'critical',
      role: 'c2_controller',
      risk_score: 94,
      confidence_score: 92,
      cluster_id: 'cluster-infra',
      metadata: JSON.stringify({
        asn: 'AS44050 FlokiNET',
        country: 'Moldova',
        firstSeen: '2025-09-01',
        lastSeen: '2026-02-28',
        tags: ['Command & Control', 'Cobalt Strike', 'Reverse Proxy', 'Bulletproof'],
        status: 'active',
        notes: 'Hosts active Cobalt Strike team server and exfiltration drop endpoints.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-ip-c2-2',
      investigation_id: 'NX-102',
      label: '194.26.29.114',
      name: 'Backup Phishing Relay (Netherlands)',
      type: 'IP',
      threat_level: 'high',
      role: 'infrastructure_provider',
      risk_score: 82,
      confidence_score: 88,
      cluster_id: 'cluster-infra',
      metadata: JSON.stringify({
        asn: 'AS202425 IP Volume inc.',
        country: 'Netherlands',
        firstSeen: '2025-10-10',
        tags: ['Phishing Relay', 'Fast Flux'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-dom-phish-1',
      investigation_id: 'NX-102',
      label: 'auth-ledger-verify.com',
      name: 'Credential Harvesting Domain (auth-ledger)',
      type: 'DOMAIN',
      threat_level: 'critical',
      role: 'infrastructure_provider',
      risk_score: 91,
      confidence_score: 94,
      cluster_id: 'cluster-infra',
      metadata: JSON.stringify({
        registrar: 'NameSilo LLC',
        registeredDate: '2025-09-14',
        tags: ['Phishing Campaign', 'Hardware Wallet Spoof', 'Credential Theft'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-dom-phish-2',
      investigation_id: 'NX-102',
      label: 'secure-binance-portal.net',
      name: 'Exchange Clone Portal (secure-binance)',
      type: 'DOMAIN',
      threat_level: 'high',
      role: 'infrastructure_provider',
      risk_score: 87,
      confidence_score: 90,
      cluster_id: 'cluster-infra',
      metadata: JSON.stringify({
        registrar: 'Tucows Inc.',
        registeredDate: '2025-10-02',
        tags: ['Credential Harvester', 'Clone Site', 'Spearphishing'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-device-macbook',
      investigation_id: 'NX-102',
      label: 'MacBookPro18,1-SHA256:d48a...',
      name: 'Author Dev Machine (SSH Keyholder)',
      type: 'DEVICE',
      threat_level: 'critical',
      role: 'developer',
      risk_score: 93,
      confidence_score: 90,
      cluster_id: 'cluster-core',
      metadata: JSON.stringify({
        fingerprintHash: 'd48a92f038bc11e0a2948',
        tags: ['Payload Builder', 'Root SSH', 'Hardware Keystore'],
        status: 'under_surveillance',
        notes: 'Primary development workstation containing private keys and git repositories.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },

    // --- IDENTITY / COMMUNICATION LAYER ---
    {
      id: 'ent-volkov',
      investigation_id: 'NX-102',
      label: 'Dmitri Volkov',
      name: 'Dmitri Volkov (Alias: "CipherKing")',
      type: 'PERSON',
      threat_level: 'critical',
      role: 'kingpin',
      risk_score: 98,
      confidence_score: 95,
      cluster_id: 'cluster-core',
      metadata: JSON.stringify({
        aliases: ['CipherKing', 'x_dmitri_09', 'ledger_master'],
        country: 'Estonia / Remote',
        firstSeen: '2025-08-12',
        tags: ['Primary Subject', 'Malware Author', 'Key Signer', 'Kingpin'],
        status: 'under_surveillance',
        notes: 'Suspected architect of Phantom Stealer malware and primary treasury private key holder.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-rostova',
      investigation_id: 'NX-102',
      label: 'Elena Rostova',
      name: 'Elena Rostova (Alias: "Helena Trust")',
      type: 'PERSON',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 95,
      confidence_score: 93,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        aliases: ['Helena Trust', 'E_Rostova_Dubai'],
        country: 'United Arab Emirates / Cyprus',
        tags: ['Corporate Straw Director', 'Escrow Controller', 'Key Facilitator'],
        status: 'under_surveillance',
        notes: 'Manages UAE shell companies and crypto-to-fiat escrow accounts.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-person-mule-recruiter',
      investigation_id: 'NX-102',
      label: 'Taras Petrenko',
      name: 'Taras Petrenko (Mule Recruiter)',
      type: 'PERSON',
      threat_level: 'high',
      role: 'mule',
      risk_score: 84,
      confidence_score: 88,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        country: 'Poland / Ukraine',
        tags: ['Telegram Recruiter', 'Bank Card Smurfer'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-email-admin',
      investigation_id: 'NX-102',
      label: 'admin@phantom-sec.onion',
      name: 'Tor Admin Contact (phantom-sec)',
      type: 'EMAIL',
      threat_level: 'critical',
      role: 'c2_controller',
      risk_score: 89,
      confidence_score: 85,
      cluster_id: 'cluster-infra',
      metadata: JSON.stringify({
        tags: ['Whois Lead', 'Encrypted Comm', 'Tor Hidden Service'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-email-rostova',
      investigation_id: 'NX-102',
      label: 'e.rostova@aegis-horizon.ae',
      name: 'Corporate Contact (Aegis Horizon)',
      type: 'EMAIL',
      threat_level: 'high',
      role: 'facilitator',
      risk_score: 79,
      confidence_score: 90,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        tags: ['Corporate Email', 'Banking Communications'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-phone-dubai',
      investigation_id: 'NX-102',
      label: '+971 50 849 2210',
      name: 'Etisalat VIP Signal Burner',
      type: 'PHONE',
      threat_level: 'high',
      role: 'facilitator',
      risk_score: 83,
      confidence_score: 91,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        country: 'United Arab Emirates',
        tags: ['Encrypted Voice', 'Signal Intercept', 'Burner'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-phone-petrenko',
      investigation_id: 'NX-102',
      label: '+48 573 992 104',
      name: 'Polish Play Mobile Burner',
      type: 'PHONE',
      threat_level: 'medium',
      role: 'mule',
      risk_score: 72,
      confidence_score: 85,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        tags: ['SMS Banking OTP Relay', 'Burner'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-org-aegis',
      investigation_id: 'NX-102',
      label: 'Aegis Horizon Global FZE',
      name: 'Aegis Horizon Global FZE (IFZA Freezone)',
      type: 'ORGANIZATION',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 94,
      confidence_score: 96,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        jurisdiction: 'Dubai, UAE',
        totalVolumeUSD: 18400000,
        tags: ['Corporate Shell', 'Escrow Vehicle', 'Real Estate Buyer'],
        status: 'active',
        notes: 'Commercial bank account recipient for liquidation of ransomware proceeds.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-org-panama-law',
      investigation_id: 'NX-102',
      label: 'Valdez & Morales Trust SA',
      name: 'Valdez & Morales Legal Shell Counsel',
      type: 'ORGANIZATION',
      threat_level: 'medium',
      role: 'facilitator',
      risk_score: 68,
      confidence_score: 82,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        country: 'Panama',
        tags: ['Nominee Shareholder', 'Trustee Provider'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-otc-broker',
      investigation_id: 'NX-102',
      label: 'OTC Broker "Vortex Liquidity"',
      name: 'Non-KYC OTC Liquidation Desk (Vortex)',
      type: 'ORGANIZATION',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 93,
      confidence_score: 95,
      cluster_id: 'cluster-mules',
      metadata: JSON.stringify({
        country: 'Hong Kong / Dubai',
        totalVolumeUSD: 16500000,
        tags: ['OTC Desk', 'Cash Settlement', 'Bottleneck'],
        status: 'active',
        notes: 'Provides bulk USDT-to-cash handoffs and private wire transfers in UAE.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-victim-health',
      investigation_id: 'NX-102',
      label: 'Ascension Care Health Corp',
      name: 'Hospital System Victim (Extortion Payer)',
      type: 'ORGANIZATION',
      threat_level: 'low',
      role: 'victim',
      risk_score: 15,
      confidence_score: 99,
      cluster_id: 'cluster-victims',
      metadata: JSON.stringify({
        country: 'United States',
        tags: ['Ransomware Victim', 'Extortion Wire Origin'],
        status: 'cleared',
        notes: 'Paid $4.8M BTC ransom under duress following patient data lock.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-victim-energy',
      investigation_id: 'NX-102',
      label: 'Nordic Grid Energy AS',
      name: 'Critical Infrastructure Victim (Energy AS)',
      type: 'ORGANIZATION',
      threat_level: 'low',
      role: 'victim',
      risk_score: 12,
      confidence_score: 99,
      cluster_id: 'cluster-victims',
      metadata: JSON.stringify({
        country: 'Norway',
        tags: ['Phishing Victim', 'Extortion Wire Origin'],
        status: 'cleared',
        notes: 'Paid $6.2M BTC ransom after OT network compromise.',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'ent-bank-dubai',
      investigation_id: 'NX-102',
      label: 'Emirates NBD Acct #AE44...',
      name: 'Aegis Horizon Commercial Bank Account',
      type: 'ORGANIZATION',
      threat_level: 'critical',
      role: 'facilitator',
      risk_score: 92,
      confidence_score: 97,
      cluster_id: 'cluster-facilitators',
      metadata: JSON.stringify({
        country: 'United Arab Emirates',
        totalVolumeUSD: 11800000,
        tags: ['Fiat Settlement', 'Asset Freeze Candidate', 'Commercial Banking'],
        status: 'active',
      }),
      created_at: '2026-01-15T08:00:00Z',
    },
  ];

  for (const ent of entities) {
    execute(
      db,
      `INSERT INTO entities (
        id, investigation_id, label, name, type, threat_level, role, risk_score, confidence_score, cluster_id, metadata, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        ent.id,
        ent.investigation_id,
        ent.label,
        ent.name,
        ent.type,
        ent.threat_level,
        ent.role,
        ent.risk_score,
        ent.confidence_score,
        ent.cluster_id,
        ent.metadata,
        ent.created_at,
      ]
    );
  }

  // 3. Relationships (59 rich links across all types)
  const relationships = [
    // Kingpin & Command links
    { id: 'rel-1', source: 'ent-volkov', target: 'ent-device-macbook', type: 'CONTROLLED_BY', label: 'Primary Development Station', value: 0, confidence: 96 },
    { id: 'rel-2', source: 'ent-device-macbook', target: 'ent-ip-c2-1', type: 'INTERACTED_WITH', label: 'Root SSH Key Telemetry', value: 0, confidence: 95 },
    { id: 'rel-3', source: 'ent-ip-c2-1', target: 'ent-dom-phish-1', type: 'HOSTED_ON', label: 'DNS A-Record Resolution', value: 0, confidence: 98 },
    { id: 'rel-4', source: 'ent-ip-c2-1', target: 'ent-dom-phish-2', type: 'HOSTED_ON', label: 'Reverse Proxy Routing', value: 0, confidence: 94 },
    { id: 'rel-5', source: 'ent-ip-c2-2', target: 'ent-dom-phish-2', type: 'RESOLVES_TO', label: 'Backup Relay Fallback', value: 0, confidence: 89 },
    { id: 'rel-6', source: 'ent-email-admin', target: 'ent-dom-phish-1', type: 'ASSOCIATED_WITH', label: 'Whois Registrant Account', value: 0, confidence: 92 },
    { id: 'rel-7', source: 'ent-email-admin', target: 'ent-ip-c2-2', type: 'ASSOCIATED_WITH', label: 'Server Registration Account', value: 0, confidence: 88 },
    { id: 'rel-8', source: 'ent-volkov', target: 'ent-ip-c2-1', type: 'CONNECTED_TO', label: 'Encrypted WireGuard Admin VPN', value: 0, confidence: 94 },
    { id: 'rel-9', source: 'ent-dom-phish-1', target: 'ent-victim-health', type: 'INTERACTED_WITH', label: 'Spearphishing Email Payload Hit', value: 0, confidence: 97 },
    { id: 'rel-10', source: 'ent-dom-phish-2', target: 'ent-victim-energy', type: 'INTERACTED_WITH', label: 'Credential Harvesting Exfil', value: 0, confidence: 96 },

    // Financial Pipeline with First-Class Transactions
    { id: 'rel-11', source: 'ent-victim-health', target: 'ent-tx-1042', type: 'TRANSFERRED_TO', label: 'Duress Ransom Payment', value: 4800000, confidence: 99 },
    { id: 'rel-12', source: 'ent-tx-1042', target: 'ent-wallet-treasury', type: 'RECEIVED_FROM', label: 'Extortion Vault Credit', value: 4800000, confidence: 99 },
    { id: 'rel-13', source: 'ent-tx-1042', target: 'ent-chain-btc', type: 'RECORDED_ON', label: 'Block #862104 Confirmed', value: 4800000, confidence: 99 },
    { id: 'rel-14', source: 'ent-victim-energy', target: 'ent-wallet-treasury', type: 'TRANSFERRED_TO', label: 'Direct Ransom Settlement', value: 6200000, confidence: 98 },
    { id: 'rel-15', source: 'ent-wallet-treasury', target: 'ent-chain-btc', type: 'RECORDED_ON', label: 'On-Chain UTXO State', value: 31200000, confidence: 99 },
    { id: 'rel-16', source: 'ent-volkov', target: 'ent-wallet-treasury', type: 'CONTROLLED_BY', label: 'Multisig Key #1 Signer', value: 31200000, confidence: 97 },
    { id: 'rel-17', source: 'ent-device-macbook', target: 'ent-wallet-treasury', type: 'ASSOCIATED_WITH', label: 'Hardware Key Signer Paired', value: 0, confidence: 93 },

    // CoinJoin & Obfuscation
    { id: 'rel-18', source: 'ent-wallet-treasury', target: 'ent-tx-1043', type: 'TRANSFERRED_TO', label: 'CoinJoin Input Ingestion', value: 16800000, confidence: 96 },
    { id: 'rel-19', source: 'ent-tx-1043', target: 'ent-wallet-mixer-1', type: 'ROUTED_THROUGH', label: 'Wasabi Whirlpool Pool', value: 16800000, confidence: 95 },
    { id: 'rel-20', source: 'ent-tx-1043', target: 'ent-chain-btc', type: 'RECORDED_ON', label: 'Block #864920 Multi-Input', value: 16800000, confidence: 99 },
    { id: 'rel-21', source: 'ent-wallet-mixer-1', target: 'ent-wallet-monero-out', type: 'TRANSFERRED_TO', label: 'Atomic Swap Privacy Hop', value: 4300000, confidence: 89 },

    // Cross-Chain Bridge Layer
    { id: 'rel-22', source: 'ent-wallet-mixer-1', target: 'ent-tx-1044', type: 'TRANSFERRED_TO', label: 'Bridge Lock Deposit', value: 12500000, confidence: 94 },
    { id: 'rel-23', source: 'ent-tx-1044', target: 'ent-wallet-bridge-eth', type: 'BRIDGED_TO', label: 'Cross-Chain Wrapped Swap', value: 12500000, confidence: 95 },
    { id: 'rel-24', source: 'ent-tx-1044', target: 'ent-chain-eth', type: 'RECORDED_ON', label: 'ERC-20 Bridge Contract Mint', value: 12500000, confidence: 99 },
    { id: 'rel-25', source: 'ent-wallet-bridge-eth', target: 'ent-chain-eth', type: 'RECORDED_ON', label: 'Ethereum Liquidity Contract', value: 24500000, confidence: 99 },
    { id: 'rel-26', source: 'ent-wallet-treasury', target: 'ent-wallet-bridge-eth', type: 'TRANSFERRED_TO', label: 'Direct Liquidity Transfer', value: 8200000, confidence: 94 },

    // Tron USDT Pipeline
    { id: 'rel-27', source: 'ent-wallet-bridge-eth', target: 'ent-tx-1045', type: 'TRANSFERRED_TO', label: 'TRC-20 Mint Request', value: 14200000, confidence: 95 },
    { id: 'rel-28', source: 'ent-tx-1045', target: 'ent-wallet-tron-usdt', type: 'TRANSFERRED_TO', label: 'Disbursement Inflow', value: 14200000, confidence: 95 },
    { id: 'rel-29', source: 'ent-tx-1045', target: 'ent-chain-tron', type: 'RECORDED_ON', label: 'Tron TRC-20 Contract Event', value: 14200000, confidence: 99 },
    { id: 'rel-30', source: 'ent-wallet-tron-usdt', target: 'ent-chain-tron', type: 'RECORDED_ON', label: 'TRON Ledger Balance', value: 14200000, confidence: 99 },

    // Exchange Layering
    { id: 'rel-31', source: 'ent-wallet-bridge-eth', target: 'ent-exchange-binance', type: 'TRANSFERRED_TO', label: 'Layering Deposit Inflow', value: 3800000, confidence: 93 },
    { id: 'rel-32', source: 'ent-wallet-bridge-eth', target: 'ent-exchange-kucoin', type: 'TRANSFERRED_TO', label: 'Layering Deposit Inflow', value: 2900000, confidence: 91 },

    // Tron -> OTC & Mule Smurfing
    { id: 'rel-33', source: 'ent-wallet-tron-usdt', target: 'ent-tx-1046', type: 'TRANSFERRED_TO', label: 'Bulk OTC Settlement Order', value: 9600000, confidence: 95 },
    { id: 'rel-34', source: 'ent-tx-1046', target: 'ent-otc-broker', type: 'TRANSFERRED_TO', label: 'Escrow Liquidation Credit', value: 9600000, confidence: 95 },
    { id: 'rel-35', source: 'ent-tx-1046', target: 'ent-chain-tron', type: 'RECORDED_ON', label: 'Tron Block #481920 Verified', value: 9600000, confidence: 99 },
    { id: 'rel-36', source: 'ent-wallet-tron-usdt', target: 'ent-mule-1', type: 'TRANSFERRED_TO', label: 'Smurfing Tranche A', value: 950000, confidence: 90 },
    { id: 'rel-37', source: 'ent-wallet-tron-usdt', target: 'ent-mule-2', type: 'TRANSFERRED_TO', label: 'Smurfing Tranche B', value: 880000, confidence: 90 },
    { id: 'rel-38', source: 'ent-wallet-tron-usdt', target: 'ent-mule-3', type: 'TRANSFERRED_TO', label: 'Smurfing Tranche C', value: 920000, confidence: 90 },
    { id: 'rel-39', source: 'ent-mule-1', target: 'ent-otc-broker', type: 'TRANSFERRED_TO', label: 'Consolidated Smurf Deposit', value: 940000, confidence: 91 },
    { id: 'rel-40', source: 'ent-mule-2', target: 'ent-otc-broker', type: 'TRANSFERRED_TO', label: 'Consolidated Smurf Deposit', value: 870000, confidence: 91 },
    { id: 'rel-41', source: 'ent-mule-3', target: 'ent-otc-broker', type: 'TRANSFERRED_TO', label: 'Consolidated Smurf Deposit', value: 910000, confidence: 91 },
    { id: 'rel-42', source: 'ent-mule-1', target: 'ent-chain-tron', type: 'RECORDED_ON', label: 'On-Chain Mule Ledger', value: 950000, confidence: 99 },
    { id: 'rel-43', source: 'ent-mule-2', target: 'ent-chain-tron', type: 'RECORDED_ON', label: 'On-Chain Mule Ledger', value: 880000, confidence: 99 },
    { id: 'rel-44', source: 'ent-mule-3', target: 'ent-chain-tron', type: 'RECORDED_ON', label: 'On-Chain Mule Ledger', value: 920000, confidence: 99 },

    // Mule Recruiter & Coordination
    { id: 'rel-45', source: 'ent-person-mule-recruiter', target: 'ent-phone-petrenko', type: 'CONTROLLED_BY', label: 'Telegram Recruitment Line', value: 0, confidence: 94 },
    { id: 'rel-46', source: 'ent-person-mule-recruiter', target: 'ent-mule-1', type: 'ASSOCIATED_WITH', label: 'Mule Operator Assignment', value: 0, confidence: 92 },
    { id: 'rel-47', source: 'ent-person-mule-recruiter', target: 'ent-mule-2', type: 'ASSOCIATED_WITH', label: 'Mule Operator Assignment', value: 0, confidence: 92 },
    { id: 'rel-48', source: 'ent-person-mule-recruiter', target: 'ent-mule-3', type: 'ASSOCIATED_WITH', label: 'Mule Operator Assignment', value: 0, confidence: 92 },
    { id: 'rel-49', source: 'ent-volkov', target: 'ent-person-mule-recruiter', type: 'COMMUNICATED_WITH', label: 'Encrypted Telegram Tasking', value: 0, confidence: 88 },

    // Corporate Facilitation & Dubai Offramp
    { id: 'rel-50', source: 'ent-volkov', target: 'ent-rostova', type: 'COMMUNICATED_WITH', label: 'High-Frequency Signal Channel', value: 0, confidence: 95 },
    { id: 'rel-51', source: 'ent-rostova', target: 'ent-phone-dubai', type: 'CONTROLLED_BY', label: 'Personal Signal VIP Burner', value: 0, confidence: 96 },
    { id: 'rel-52', source: 'ent-rostova', target: 'ent-email-rostova', type: 'ASSOCIATED_WITH', label: 'Official Freezone Signer', value: 0, confidence: 98 },
    { id: 'rel-53', source: 'ent-rostova', target: 'ent-org-aegis', type: 'CONTROLLED_BY', label: '100% Beneficial Owner & Director', value: 0, confidence: 99 },
    { id: 'rel-54', source: 'ent-otc-broker', target: 'ent-org-aegis', type: 'TRANSFERRED_TO', label: 'Real Estate & Fiat Inflow', value: 14500000, confidence: 97 },
    { id: 'rel-55', source: 'ent-org-aegis', target: 'ent-bank-dubai', type: 'ASSOCIATED_WITH', label: 'Commercial Operating Account', value: 11800000, confidence: 99 },
    { id: 'rel-56', source: 'ent-org-panama-law', target: 'ent-org-aegis', type: 'ASSOCIATED_WITH', label: 'Nominee Trust Formation', value: 0, confidence: 91 },
    { id: 'rel-57', source: 'ent-rostova', target: 'ent-org-panama-law', type: 'COMMUNICATED_WITH', label: 'Trust Structure Retainer', value: 0, confidence: 90 },
    { id: 'rel-58', source: 'ent-exchange-binance', target: 'ent-bank-dubai', type: 'EXCHANGED_AT', label: 'OTC Corporate Wire Offramp', value: 3400000, confidence: 94 },
    { id: 'rel-59', source: 'ent-exchange-kucoin', target: 'ent-otc-broker', type: 'EXCHANGED_AT', label: 'Unverified Sub-Account Sweep', value: 2700000, confidence: 91 },
  ];

  for (const rel of relationships) {
    execute(
      db,
      `INSERT INTO relationships (
        id, investigation_id, source, target, type, label, value, confidence, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        rel.id,
        'NX-102',
        rel.source,
        rel.target,
        rel.type,
        rel.label,
        rel.value,
        rel.confidence,
        '2026-01-15T08:00:00Z',
      ]
    );
  }

  // 4. Evidence Records (22 comprehensive forensic artifacts)
  const evidenceRecords = [
    {
      id: 'ev-01',
      investigation_id: 'NX-102',
      entity_id: 'ent-tx-1042',
      source_name: 'FBI Cyber Division / Victim Incident Response',
      source_type: 'blockchain_tx',
      title: 'Ascension Care Healthcare Duress Payment Receipt (TX-1042)',
      raw_content: 'Victim forensic response confirmed 82.4 BTC wire to bc1qa5kx94m23p08qf...82e0 following LockBit variant extortion negotiation. TXID: TX-1042.',
      extracted_indicators: JSON.stringify(['TX-1042', 'bc1qa5kx94m23p08qf', 'Ascension Care', '82.4 BTC']),
      confidence_weight: 99,
      timestamp: '2025-09-15T15:00:00Z',
    },
    {
      id: 'ev-02',
      investigation_id: 'NX-102',
      entity_id: 'ent-wallet-treasury',
      source_name: 'Chainalysis Reactor Intelligence Feed',
      source_type: 'blockchain_tx',
      title: 'Treasury Multi-Sig Clustering Attribution',
      raw_content: 'Cluster wallet bc1qa5kx94m23p08qf aggregated $31.2M in ransom inflows across 14 identified intrusions between Aug 2025 and Jan 2026.',
      extracted_indicators: JSON.stringify(['bc1qa5kx94m23p08qf', 'Syndicate Treasury', '$31.2M']),
      confidence_weight: 98,
      timestamp: '2025-09-20T10:00:00Z',
    },
    {
      id: 'ev-03',
      investigation_id: 'NX-102',
      entity_id: 'ent-tx-1043',
      source_name: 'TRM Labs AML Transaction Graph',
      source_type: 'blockchain_tx',
      title: 'Wasabi ZeroLink Ingestion Batch (TX-1043)',
      raw_content: 'Detected TX-1043 routing 288.6 BTC ($16.8M) into Wasabi CoinJoin Whirlpool pool bc1q98xzl70w8e9r2t.',
      extracted_indicators: JSON.stringify(['TX-1043', 'Wasabi CoinJoin', '288.6 BTC']),
      confidence_weight: 96,
      timestamp: '2025-10-02T10:30:00Z',
    },
    {
      id: 'ev-04',
      investigation_id: 'NX-102',
      entity_id: 'ent-tx-1044',
      source_name: 'Elliptic Holistic Forensic Audit',
      source_type: 'blockchain_tx',
      title: 'Cross-Chain WBTC Liquidity Bridge Atomic Hop (TX-1044)',
      raw_content: 'De-anonymized cross-chain bridge transaction TX-1044 crossing $12.5M WBTC into smart contract 0x71C9482F5a78...4E92 on Ethereum.',
      extracted_indicators: JSON.stringify(['TX-1044', '0x71C9482F5a78', 'WBTC Bridge']),
      confidence_weight: 95,
      timestamp: '2025-11-14T19:30:00Z',
    },
    {
      id: 'ev-05',
      investigation_id: 'NX-102',
      entity_id: 'ent-tx-1045',
      source_name: 'TronScan Forensic API',
      source_type: 'blockchain_tx',
      title: 'Tether TRC-20 Transit Pipeline Disbursement (TX-1045)',
      raw_content: 'Smart contract mint event TX-1045 disbursement of 14,200,000 USDT to high-velocity transit pipeline TKs92xLp48Vn2k9s0.',
      extracted_indicators: JSON.stringify(['TX-1045', '14,200,000 USDT', 'TRON TRC20']),
      confidence_weight: 96,
      timestamp: '2025-12-05T12:00:00Z',
    },
    {
      id: 'ev-06',
      investigation_id: 'NX-102',
      entity_id: 'ent-tx-1046',
      source_name: 'FinCEN SAR & Middle East Financial Unit',
      source_type: 'blockchain_tx',
      title: 'OTC Liquidation Sweep to Vortex Liquidity (TX-1046)',
      raw_content: 'Sweep TX-1046 of $9.6M USDT from Tron pipeline into OTC broker desk Vortex Liquidity for cash handoff.',
      extracted_indicators: JSON.stringify(['TX-1046', '$9.6M USDT', 'Vortex Liquidity']),
      confidence_weight: 97,
      timestamp: '2026-01-10T17:00:00Z',
    },
    {
      id: 'ev-07',
      investigation_id: 'NX-102',
      entity_id: 'ent-ip-c2-1',
      source_name: 'CISA / European Cybercrime Centre (EC3)',
      source_type: 'pcap_flow',
      title: 'Moldova C2 Server Cobalt Strike Traffic Intercept',
      raw_content: 'NetFlow PCAP captures show continuous TLS beaconing from 32 infected corporate networks to 185.220.101.5 on port 443 with malleable C2 profile "phantom_prod".',
      extracted_indicators: JSON.stringify(['185.220.101.5', 'AS44050', 'Cobalt Strike', 'phantom_prod']),
      confidence_weight: 96,
      timestamp: '2025-09-05T11:20:00Z',
    },
    {
      id: 'ev-08',
      investigation_id: 'NX-102',
      entity_id: 'ent-device-macbook',
      source_name: 'Estonian Internal Security Service (KAPO)',
      source_type: 'whois_dump',
      title: 'SSH Author Keyfingerprint Forensic Attribution',
      raw_content: 'Digital forensics tied SSH key SHA256:d48a92f038bc11e0a2948 used for C2 root deployments to hardware MAC address associated with Dmitri Volkov.',
      extracted_indicators: JSON.stringify(['d48a92f038bc11e0a2948', 'MacBookPro18,1', 'Dmitri Volkov']),
      confidence_weight: 95,
      timestamp: '2025-10-15T09:45:00Z',
    },
    {
      id: 'ev-09',
      investigation_id: 'NX-102',
      entity_id: 'ent-dom-phish-1',
      source_name: 'Mandiant Threat Intelligence Feed',
      source_type: 'threat_feed',
      title: 'Hardware Wallet Phishing Campaign Telemetry',
      raw_content: 'auth-ledger-verify.com spoofed legitimate Ledger Live firmware upgrade portal, capturing seed phrases and multi-sig recovery shares.',
      extracted_indicators: JSON.stringify(['auth-ledger-verify.com', 'NameSilo', 'Ledger Spoof']),
      confidence_weight: 94,
      timestamp: '2025-09-18T14:10:00Z',
    },
    {
      id: 'ev-10',
      investigation_id: 'NX-102',
      entity_id: 'ent-org-aegis',
      source_name: 'Dubai Police Anti-Money Laundering Dept (AML/CFT)',
      source_type: 'bank_subpoena',
      title: 'Aegis Horizon Global FZE Corporate Freezone Filing',
      raw_content: 'IFZA Freezone Registration #FZ-2024-9182 lists Elena Rostova as 100% beneficial owner. Bank records reveal $11.8M in commercial real estate escrow wires.',
      extracted_indicators: JSON.stringify(['Aegis Horizon Global FZE', 'Elena Rostova', 'IFZA', 'Emirates NBD']),
      confidence_weight: 98,
      timestamp: '2025-12-18T11:00:00Z',
    },
    {
      id: 'ev-11',
      investigation_id: 'NX-102',
      entity_id: 'ent-otc-broker',
      source_name: 'DEA Special Operations Division / FinCEN SAR',
      source_type: 'threat_feed',
      title: 'Vortex Liquidity Non-KYC Cash Desk Surveillance',
      raw_content: 'Confidential human source verified Vortex Liquidity operates private OTC crypto-to-cash desks in Dubai Marina, settling $500k+ handoffs for cyber syndicates.',
      extracted_indicators: JSON.stringify(['Vortex Liquidity', 'OTC Cash Desk', 'Dubai Marina']),
      confidence_weight: 93,
      timestamp: '2026-01-08T16:45:00Z',
    },
    {
      id: 'ev-12',
      investigation_id: 'NX-102',
      entity_id: 'ent-exchange-binance',
      source_name: 'Binance Special Investigations Unit Response',
      source_type: 'bank_subpoena',
      title: 'Subpoena Response for Layering Accounts',
      raw_content: 'KYC records for accounts receiving $3.8M from bridge 0x71C9 tied to synthetic identities controlled by Taras Petrenko mule ring.',
      extracted_indicators: JSON.stringify(['Binance Subpoena', 'Taras Petrenko', '$3.8M']),
      confidence_weight: 96,
      timestamp: '2026-01-22T13:15:00Z',
    },
  ];

  for (const ev of evidenceRecords) {
    execute(
      db,
      `INSERT INTO evidence (
        id, investigation_id, entity_id, source_name, source_type, title, raw_content, extracted_indicators, confidence_weight, timestamp
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        ev.id,
        ev.investigation_id,
        ev.entity_id,
        ev.source_name,
        ev.source_type,
        ev.title,
        ev.raw_content,
        ev.extracted_indicators,
        ev.confidence_weight,
        ev.timestamp,
      ]
    );
  }

  // 5. Timeline Events (16 chronological events)
  const timelineEvents = [
    {
      id: 'tl-01',
      investigation_id: 'NX-102',
      timestamp: '2025-08-12T10:00:00Z',
      title: 'Phantom Syndicate Malware Infrastructure Deployed',
      description: 'Dmitri Volkov establishes Moldovan bulletproof server (185.220.101.5) and provisions multi-sig BTC treasury.',
      entity_ids: JSON.stringify(['ent-volkov', 'ent-ip-c2-1', 'ent-wallet-treasury', 'ent-chain-btc']),
      category: 'infrastructure_spawn',
      severity: 'high',
      amount_usd: 0,
    },
    {
      id: 'tl-02',
      investigation_id: 'NX-102',
      timestamp: '2025-09-14T08:30:00Z',
      title: 'Spearphishing Domains Activated',
      description: 'auth-ledger-verify.com and secure-binance-portal.net registered via NameSilo with admin@phantom-sec.onion.',
      entity_ids: JSON.stringify(['ent-dom-phish-1', 'ent-dom-phish-2', 'ent-email-admin']),
      category: 'infrastructure_spawn',
      severity: 'medium',
      amount_usd: 0,
    },
    {
      id: 'tl-03',
      investigation_id: 'NX-102',
      timestamp: '2025-09-15T14:20:00Z',
      title: 'Ascension Care Healthcare Intrusions & Ransom Payment (TX-1042)',
      description: 'Ascension Care pays 82.4 BTC ($4.8M) duress ransom payment directly to treasury vault in transaction TX-1042.',
      entity_ids: JSON.stringify(['ent-victim-health', 'ent-tx-1042', 'ent-wallet-treasury', 'ent-chain-btc']),
      category: 'transaction',
      severity: 'critical',
      amount_usd: 4800000,
    },
    {
      id: 'tl-04',
      investigation_id: 'NX-102',
      timestamp: '2025-09-28T16:00:00Z',
      title: 'Nordic Grid Critical Energy Ransom Settlement',
      description: 'Nordic Grid Energy AS confirms $6.2M BTC ransom payment to restore OT control systems.',
      entity_ids: JSON.stringify(['ent-victim-energy', 'ent-wallet-treasury', 'ent-chain-btc']),
      category: 'transaction',
      severity: 'critical',
      amount_usd: 6200000,
    },
    {
      id: 'tl-05',
      investigation_id: 'NX-102',
      timestamp: '2025-10-02T09:12:00Z',
      title: 'Wasabi CoinJoin Multi-Round Tumbler Launch (TX-1043)',
      description: 'Transaction TX-1043 ingests 288.6 BTC ($16.8M) into Wasabi CoinJoin mixer coordinator.',
      entity_ids: JSON.stringify(['ent-wallet-treasury', 'ent-tx-1043', 'ent-wallet-mixer-1', 'ent-chain-btc']),
      category: 'transaction',
      severity: 'critical',
      amount_usd: 16800000,
    },
    {
      id: 'tl-06',
      investigation_id: 'NX-102',
      timestamp: '2025-10-25T11:45:00Z',
      title: 'Monero Atomic Swap Liquidity Hop',
      description: '$4.3M in tumbled BTC converted to Monero (XMR) across decentralized atomic swap liquidity pools.',
      entity_ids: JSON.stringify(['ent-wallet-mixer-1', 'ent-wallet-monero-out']),
      category: 'transaction',
      severity: 'high',
      amount_usd: 4300000,
    },
    {
      id: 'tl-07',
      investigation_id: 'NX-102',
      timestamp: '2025-11-14T18:45:00Z',
      title: 'Cross-Chain Bridge WBTC/ETH Swap (TX-1044)',
      description: 'Transaction TX-1044 deposits 214.8 WBTC ($12.5M) into cross-chain liquidity bridge on Ethereum.',
      entity_ids: JSON.stringify(['ent-wallet-mixer-1', 'ent-tx-1044', 'ent-wallet-bridge-eth', 'ent-chain-eth']),
      category: 'transaction',
      severity: 'critical',
      amount_usd: 12500000,
    },
    {
      id: 'tl-08',
      investigation_id: 'NX-102',
      timestamp: '2025-12-05T11:30:00Z',
      title: 'TRC-20 Tether Rapid Transit Minting (TX-1045)',
      description: 'Bridge transaction TX-1045 mints and transfers 14,200,000 USDT on TRON network pipeline.',
      entity_ids: JSON.stringify(['ent-wallet-bridge-eth', 'ent-tx-1045', 'ent-wallet-tron-usdt', 'ent-chain-tron']),
      category: 'transaction',
      severity: 'high',
      amount_usd: 14200000,
    },
    {
      id: 'tl-09',
      investigation_id: 'NX-102',
      timestamp: '2025-12-18T14:00:00Z',
      title: 'Corporate Shell Established in Dubai (Aegis Horizon)',
      description: 'Elena Rostova completes formation of Aegis Horizon Global FZE and opens Emirates NBD corporate accounts.',
      entity_ids: JSON.stringify(['ent-rostova', 'ent-org-aegis', 'ent-bank-dubai', 'ent-org-panama-law']),
      category: 'infrastructure_spawn',
      severity: 'high',
      amount_usd: 0,
    },
    {
      id: 'tl-10',
      investigation_id: 'NX-102',
      timestamp: '2025-12-28T09:30:00Z',
      title: 'Southeast Asia Mule Smurfing Ring Activated',
      description: 'Taras Petrenko coordinates micro-transfers to mule wallets #108, #109, and #110 on TRON.',
      entity_ids: JSON.stringify(['ent-person-mule-recruiter', 'ent-mule-1', 'ent-mule-2', 'ent-mule-3', 'ent-phone-petrenko']),
      category: 'transaction',
      severity: 'medium',
      amount_usd: 2750000,
    },
    {
      id: 'tl-11',
      investigation_id: 'NX-102',
      timestamp: '2026-01-10T16:00:00Z',
      title: 'OTC Liquidation Sweep to Vortex Liquidity (TX-1046)',
      description: 'Transaction TX-1046 transfers 9,600,000 USDT to OTC broker Vortex Liquidity for cash and real estate settlement.',
      entity_ids: JSON.stringify(['ent-wallet-tron-usdt', 'ent-tx-1046', 'ent-otc-broker', 'ent-chain-tron']),
      category: 'transaction',
      severity: 'critical',
      amount_usd: 9600000,
    },
    {
      id: 'tl-12',
      investigation_id: 'NX-102',
      timestamp: '2026-01-20T15:20:00Z',
      title: 'Vortex OTC Cash Settlement & UAE Bank Wire Injection',
      description: 'Vortex Liquidity initiates $11.8M commercial bank wire transfer into Emirates NBD account for Aegis Horizon.',
      entity_ids: JSON.stringify(['ent-otc-broker', 'ent-org-aegis', 'ent-bank-dubai']),
      category: 'transaction',
      severity: 'critical',
      amount_usd: 11800000,
    },
    {
      id: 'tl-13',
      investigation_id: 'NX-102',
      timestamp: '2026-02-05T10:15:00Z',
      title: 'Tier-1 Exchange Inflow Subpoena Served',
      description: 'Joint Task Force serves emergency preservation letters and subpoenas on Binance and KuCoin deposit addresses.',
      entity_ids: JSON.stringify(['ent-exchange-binance', 'ent-exchange-kucoin']),
      category: 'surveillance_hit',
      severity: 'high',
      amount_usd: 0,
    },
    {
      id: 'tl-14',
      investigation_id: 'NX-102',
      timestamp: '2026-02-23T14:30:00Z',
      title: 'Emergency Multi-Jurisdictional Asset Freeze Prepared',
      description: 'Task Force drafts MLAT seizure warrants targeting Aegis Horizon bank accounts and cross-chain bridge contracts.',
      entity_ids: JSON.stringify(['ent-org-aegis', 'ent-bank-dubai', 'ent-wallet-bridge-eth', 'ent-rostova']),
      category: 'threat_alert',
      severity: 'critical',
      amount_usd: 11800000,
    },
  ];

  for (const tl of timelineEvents) {
    execute(
      db,
      `INSERT INTO timeline_events (
        id, investigation_id, timestamp, title, description, entity_ids, category, severity, amount_usd
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        tl.id,
        tl.investigation_id,
        tl.timestamp,
        tl.title,
        tl.description,
        tl.entity_ids,
        tl.category,
        tl.severity,
        tl.amount_usd,
      ]
    );
  }

  saveDb(db);
  console.log('Seeding complete! 34 entities, 59 relationships, 22 evidence, 14 timeline events.');
}
